name: Node CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        working-directory: "./cli"
        run: yarn
      - name: lint
        working-directory: "./cli"
        run: yarn lint
      - name: build
        working-directory: "./cli"
        run: yarn build
  schematics:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        working-directory: "./schematics"
        run: yarn
      - name: lint
        working-directory: "./schematics"
        run: yarn lint
      - name: test
        working-directory: "./schematics"
        run: yarn test
      - name: build
        working-directory: "./schematics"
        run: yarn build
